### ISSUE TITLE
Amount shown on Woohoo did not match the transferred amount entered.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#56]
"5/9/22 freeosgov2 frontend v0.2.12 backend v0.9.51 iteration 461762
Transfer 1.2345 FREEOS from verovera to alanappleton. 
Transfer was successful. However, on Woohoo pop up, the amount was showing as 1.23 instead of 1.2345. Also it doesn't show the token being transferred i.e. 1.23 instead of 1.2345 FREEOS.

Screenshot taken from another scenario when transferring o.2345 FREEOS from alanappleton to verovera.
<img width="518" alt="Screen Shot 2022-09-05 at 1 53 13 PM" src="https://user-images.githubusercontent.com/77765830/188345243-d654d869-84ac-4afd-b347-804afcf71b2e.png">

**Comment by conorseed** [comment]
Sooooo... the number that's shown in the "Woohoo" dialog is using the number abbreviation component we built for issue #31. We added it in to the dialog to fix issue #41. That means for numbers under 1000, they're shortened to 2 decimal places. Numbers over 1000 are shorted to three figures (e.g. 1.23K, 43.5M etc). So what you've detailed as far as the number goes is expected behaviour with regards to the fixes we've implemented. 

Should we maybe fix it so that numbers under a certain figure, say 10?, always show the token precision? In this case that would be 4 decimal places? Or should this stay as is?

---

Working on a fix for the currency issue though. Will commit once we have a fix for both issues here.

**Comment by judytan21** [comment]
6/9/22 Retest. freeosgov2 frontend v0.2.15 backend v0.9.52. Transfer of 0.2345 FREEOS is now showing correctly on the Woohoo pop up. Fixed.
As per discussion with JeromeK at standup today, the following rules shall apply when displaying the amount
on Woohoo pop up. 
1) If amount is < 100 FREEOS, then show 4 decimal places. 
2) If amount is < 1000 FREEOS then abbreviated to 2 dec places.
3) Amounts over 1000 are shortened to three figures (e.g. 1.23K, 43.5M etc)
<img width="518" alt="Screen Shot 2022-09-06 at 1 37 13 PM" src="https://user-images.githubusercontent.com/77765830/188529746-fd824351-17a1-4b1f-bbf8-c937d71ebff7.png">
<img width="518" alt="Screen Shot 2022-09-06 at 2 02 35 PM" src="https://user-images.githubusercontent.com/77765830/188531532-89389342-5927-41ba-ba0b-222d39d18aae.png">
